import type React from 'react';

export const harnessStyles = {
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  } as React.CSSProperties,
  backLink: {
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: 'var(--font-base)',
    background: 'none',
    border: 'none',
    fontFamily: 'var(--font)',
    textDecoration: 'underline',
  } as React.CSSProperties,
  badges: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    marginBottom: 16,
    flexWrap: 'wrap',
  } as React.CSSProperties,
  input: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    color: 'var(--text)',
    padding: '8px 12px',
    fontSize: 'var(--font-lg)',
    fontWeight: 600,
    fontFamily: 'var(--font)',
    width: '100%',
  } as React.CSSProperties,
  textarea: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    color: 'var(--text)',
    padding: 12,
    fontFamily: 'var(--mono)',
    fontSize: 'var(--font-base)',
    width: '100%',
    minHeight: 400,
    resize: 'vertical' as const,
  } as React.CSSProperties,
  field: {
    marginBottom: 20,
  } as React.CSSProperties,
  label: {
    display: 'block',
    fontSize: 'var(--font-sm)',
    fontWeight: 500,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: 6,
  } as React.CSSProperties,
  checkboxRow: {
    display: 'flex',
    gap: 16,
    alignItems: 'center',
    marginBottom: 20,
  } as React.CSSProperties,
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    fontSize: 'var(--font-base)',
  } as React.CSSProperties,
  versionItem: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '10px 14px',
    marginBottom: 8,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'background 0.15s',
  } as React.CSSProperties,
  actions: {
    display: 'flex',
    gap: 8,
    marginTop: 20,
  } as React.CSSProperties,
} as const;
